[package]
name = "project"
version = "0.1.0"
authors = ["Perrard Alex <perrardalex@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.0"
bit-vec = "0.6.1"
bitreader = "0.3.2"
